export const ACCOUNT_REPOSITORY = Symbol("AccountRepository")
export const CREATE_ACCOUNT_USECASE = Symbol("CreateAccountUseCase")
export const GET_ME_USECASE = Symbol("GetMeUseCase")
export const ACCOUNT_SERVICE = Symbol("AccountService")
export const UPDATE_ACCOUNT_USECASE = Symbol("UpdateAccountUseCase")
export const GET_ACCOUNT_BY_EMAIL_USECASE = Symbol("GetAccountByEmailUseCase")